In [4]:
import numpy as np

In [2]:
np.zeroes(1)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [3]:
np.zero(1)

AttributeError: module 'numpy' has no attribute 'zero'

In [4]:
np.zeros(1)

array([0.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
list(np.zeros(10))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [7]:
np.zeros(10, dtype=dtype.Int16)

NameError: name 'dtype' is not defined

In [9]:
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [10]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.zeros((10,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [12]:
np.array([])

array([], dtype=float64)

In [13]:
np.array([2,3,5])

array([2, 3, 5])

In [14]:
6 % np.array([2,3,5])

array([0, 0, 1])

In [15]:
7 % np.array([2,3,5])

array([1, 1, 2])

In [16]:
np.sum(6 % np.array([2,3,5]))

1

In [17]:
a = 6 % np.array([2,3,5])

In [18]:
a

array([0, 0, 1])

In [19]:
a[2]

1

In [20]:
a > 0

array([False, False,  True])

In [21]:
a == 0

array([ True,  True, False])

In [22]:
np.asarray(a > 0)

array([False, False,  True])

In [23]:
a > 2

array([False, False, False])

In [24]:
np.any

<function numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)>

In [25]:
np.any(a)

True

In [26]:
np.where

<function numpy.where>

In [29]:
np.where(a > 0)

(array([2]),)

In [83]:
def primes(high):
    p = np.zeros(high+1, dtype=bool)
    p[2] = True
    i = 3
    while i <= high:
        p[i] = np.min(i % np.flatnonzero(p[:i+1])) > 0
        i += 1
    
    return np.flatnonzero(p)


In [84]:
primes(10)

array([2, 3, 5, 7])

In [86]:
primes(101)

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101])

In [91]:
%time p1m = primes(100000)

CPU times: user 6.23 s, sys: 20.4 ms, total: 6.25 s
Wall time: 6.25 s


In [1]:
def primes2(high):
    p = np.zeros(high+1, dtype=bool)
    p[2] = True
    i = 3
    while i <= high:
        p[i] = np.all(i % np.flatnonzero(p))
        i += 1
    
    return np.flatnonzero(p)

In [103]:
%time p2m = primes2(200000)

CPU times: user 25.3 s, sys: 90.6 ms, total: 25.4 s
Wall time: 25.4 s


In [102]:
%time primes2(10)

CPU times: user 140 µs, sys: 9 µs, total: 149 µs
Wall time: 152 µs


array([2, 3, 5, 7])

In [97]:
np.any([0, 0, 1])

True

In [5]:
primes2(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])